dailyplan_index:
    path:     /
    defaults: { _controller: "EntitiesBundle:DailyPlan:index" }
    methods:  GET

dailyplan_show:
    path:     /{id}/show
    defaults: { _controller: "EntitiesBundle:DailyPlan:show" }
    methods:  GET

dailyplan_new:
    path:     /new
    defaults: { _controller: "EntitiesBundle:DailyPlan:new" }
    methods:  [GET, POST]

dailyplan_edit:
    path:     /{id}/edit
    defaults: { _controller: "EntitiesBundle:DailyPlan:edit" }
    methods:  [GET, POST]

dailyplan_delete:
    path:     /{id}/delete
    defaults: { _controller: "EntitiesBundle:DailyPlan:delete" }
    methods:  DELETE
