event_index:
    path:     /
    defaults: { _controller: "EntitiesBundle:Event:index" }
    methods:  GET

event_show:
    path:     /{id}/show
    defaults: { _controller: "EntitiesBundle:Event:show" }
    methods:  GET

event_new:
    path:     /new
    defaults: { _controller: "EntitiesBundle:Event:new" }
    methods:  [GET, POST]

event_edit:
    path:     /edit
    defaults: { _controller: "EntitiesBundle:Event:edit" }
    methods:  [GET, POST]

event_delete:
    path:     /delete
    defaults: { _controller: "EntitiesBundle:Event:delete" }
    methods:  [POST]

event_all:
    path:       /all
    defaults:   {  _controller: "EntitiesBundle:Event:all"}
    methods:    GET
