task_index:
    path:     /
    defaults: { _controller: "EntitiesBundle:Task:index" }
    methods:  GET

task_show:
    path:     /{id}/show
    defaults: { _controller: "EntitiesBundle:Task:show" }
    methods:  GET

task_new:
    path:     /new
    defaults: { _controller: "EntitiesBundle:Task:new" }
    methods:  [GET, POST]

task_edit:
    path:     /{id}/edit
    defaults: { _controller: "EntitiesBundle:Task:edit" }
    methods:  [GET, POST]

task_delete:
    path:     /{id}/delete
    defaults: { _controller: "EntitiesBundle:Task:delete" }
    methods:  DELETE
