timetask_index:
    path:     /
    defaults: { _controller: "EntitiesBundle:TimeTask:index" }
    methods:  GET

timetask_show:
    path:     /{id}/show
    defaults: { _controller: "EntitiesBundle:TimeTask:show" }
    methods:  GET

timetask_new:
    path:     /new
    defaults: { _controller: "EntitiesBundle:TimeTask:new" }
    methods:  [GET, POST]

timetask_edit:
    path:     /edit
    defaults: { _controller: "EntitiesBundle:TimeTask:edit" }
    methods:  [GET, POST]
timetask_all:
    path:     /all
    defaults: { _controller: "EntitiesBundle:TimeTask:all" }
    methods:  GET

timetask_delete:
    path:     /delete
    defaults: { _controller: "EntitiesBundle:TimeTask:delete" }
    methods:  [POST]
