user_index:
    path:     /
    defaults: { _controller: "EntitiesBundle:User:index" }
    methods:  GET
user_all:
    path:     /all
    defaults: { _controller: "EntitiesBundle:User:index" }
    methods:  GET

user_show:
    path:     /{id}/show
    defaults: { _controller: "EntitiesBundle:User:show" }
    methods:  GET

user_new:
    path:     /new
    defaults: { _controller: "EntitiesBundle:User:new" }
    methods:  [GET, POST]

user_edit:
    path:     /edit
    defaults: { _controller: "EntitiesBundle:User:edit" }
    methods:  [GET, POST]

user_delete:
    path:     /{id}/delete
    defaults: { _controller: "EntitiesBundle:User:delete" }
    methods:  DELETE
