<?php

namespace EntitiesBundle\Repository;

/**
 * DailyPlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DailyPlanRepository extends \Doctrine\ORM\EntityRepository
{
}
