<?php

namespace EntitiesBundle\Repository;

/**
 * TriggerTaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TriggerTaskRepository extends \Doctrine\ORM\EntityRepository
{
}
