<?php

namespace EntitiesBundle\Repository;

/**
 * TrigggerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrigggerRepository extends \Doctrine\ORM\EntityRepository
{
}
